
version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
    # Hier wird der lokale Ordner "data" im Container eingebunden!
      - ./data:/app/data   # Hier wird der lokale Ordner "data" im Container eingebunden!